# Generated by Django 4.0.6 on 2022-07-28 03:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp2', '0002_rename_task_task1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task1',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='file', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'gif', 'jpeg', 'bmp', 'ai', 'eps'])]),
        ),
    ]
