# Generated by Django 4.0.6 on 2022-08-03 05:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp2', '0004_remove_task1_file_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='task1',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='file', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'gif', 'jpeg', 'bmp', 'ai', 'eps'])]),
        ),
        migrations.DeleteModel(
            name='File',
        ),
    ]
