# Generated by Django 4.0.6 on 2022-08-05 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp2', '0006_remove_task1_file_taskfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='file')),
            ],
        ),
        migrations.CreateModel(
            name='Texts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instruction', models.CharField(max_length=30)),
                ('ref_no', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='taskfile',
            name='task1',
        ),
        migrations.DeleteModel(
            name='Task1',
        ),
        migrations.DeleteModel(
            name='TaskFile',
        ),
        migrations.AddField(
            model_name='image',
            name='img',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp2.texts'),
        ),
    ]
